# Configurações de conexão com SQL Server
spring.datasource.url=jdbc:sqlserver://Briet\\SQLEXPRESS;databaseName=briet;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@mateusbriet040923
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Opcional: configurações úteis para desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.hibernate.ddl-auto=update   # ou create, validate, none - use com cuidado!
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect